dist: bionic
language: python
install:
- wget https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
- sudo dpkg -i vagrant_2.2.2_x86_64.deb
- pip install -r .requirements.txt
before_script:
- vagrant plugin install vagrant-aws
- ssh-keygen -y -f ~/.vagrant.d/insecure_private_key > ~/.vagrant.d/insecure_private_key.pub
- ln -s ./ JoergFiedler.freebsd-jailed-joomla
script:
- ansible-lint .
- yamllint .
- ansible-galaxy install -p ./ -r .requirements.yml
- vagrant box add JoergFiedler/FreeBSD-12 --provider aws
- vagrant up --provider aws
- host=$(vagrant ssh-config |grep HostName |awk '{print $2}')
- test $(curl -w %{http_code} https://${host}/installation/index.php -o /dev/null --insecure) == "200"
- test $(sftp -P 10022 -o StrictHostKeyChecking=no -i ~/.vagrant.d/insecure_private_key
  sftp_local@${host} <<< $'ls -l' |grep webroot |wc -l) == "1"
after_script:
- vagrant destroy -f
notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
env:
  global:
  - secure: GlTjylAGKcRJubGalHjWBJmYUcobdg7ey27j2ELBDZxg3Qcupi6tfs4k+HPFDNCwPqsnt6/xXJYCXBydkEL6Mx5PupT1w+zZAPwVftPpU5dIctj6BXsNH5crlJhFE8MguR4nj6RcRZxXQLhAhSez1fTKYNYJVZsoxyjhudQe0Ml82BAuLxQyIcS/JyD0mV6qUcnWV/+HrdoZMqM/I4z9wE7yFm2fQCJoOptJXk2S/lR1pl+oiju5nZnmn3UZI+IzvDI3lcnXwY+yP1fmIMNXZY/wsNsb/+eE6ZCWPaWD0rXDlvWykHZgOhiExz0qyLb8dO3tTrHm3Tkq2xW1LbIQfdO/z3AcbzbDgGL8AHu8RZL+qKcqkN7+i1RngaliBCC0WuVJ+GOxV/sb43cTFr7s3/tlvVki3ol2uEUtxPV49bLlipOaYxirsRdGH9tvS5sU6y9jFqDf9jQ64RatzIbFAbJxy8yECrhKL6WVbM7R8aMN/8C94d79ScW9mmLZaf7SJyV72jzmeWTnDHA1zNwwB1XqFv2THmQBQorVBUmeYYBNry4s3qxRmYvzrRKnVkYcdx3mBq/qg5zfAND+dE9Mo0xTInLKRVCYRD53Lmk/1Gu+4Mv3Jvr7t+bMmXlD7w9qpjXOQ17BuUB0RqPCRTtKKP82+5VPI/3kgL1UPJ7JDO0=
  - secure: fjRw3mM69i86POCwL5rKcPR8rD0dKFiSgTYp+6OgSMhqOc9mg25d8RwZFAMNHMGfGmF0B+tUisiZCrZHDN9oZUhDZXMZZe610NMDECGXM/0JFzlyUx/Y7m6aE/m5ygdT8so1ZKpCZC7eVqx3T3nusb95lOf0sv9L4hKUj6lU1QsiRqrHMlaEvQ1dnIX3jGh+OKklvOELHOilf1VZTQyowOlRJdmPCmS+1uaPnxHrdaFHkQzLonU35+GK0QvbiY2xtm///bYsOzdK+iQ5GCKqnvkK83LighUQX0lgyQtuVEqeH7p4qwbdaZHNr7rprQrjjwGtJgEmNsTiT0Qtun97Y1tN47RnmjWSTDq0wtTx37/Q15aOPmxzucV3VWEGrQ+GglNk1lKOb8ZXMT2qxM5Gv38c1nw5IyIvMq1+LI2Yq+nGBuV19mMnqEqhM01XKW/40IhBbTGht4A/fPmrSLv+oTFRCdhsQP1v1y8Tqn4akxbDBcH8dHaj3g0fq/lD37kzSwGHrvhHyYUoLhcL0Ka7CU6p9j3x5+NyqdsK/tMYO0EPpKXCnGyOVN+CaxW+nZKXwKgXTRMHF2Fwb6QZPCd8iB/W50BTcXBch0Jk24BPpx7mR2rVhO07u9EoTd8jRbEZFD7JSifj3dcvTAU7fjPD9gsM6XJTTNJKg1RmuvBZA4M=
