---
- name: Create Jommla database
  mysql_db: name=joomla_{{ server_name_ }}
            login_host={{ joomla_db_host }}
            login_password={{ joomla_db_host_password }}
            login_user={{ joomla_db_host_user }}
            state=present

- name: Create MariaDB joomla user
  mysql_user: name={{ joomla_db_user }}
              encrypted=no
              host={{ jail_net_ip }}
              login_host={{ joomla_db_host }}
              login_password={{ joomla_db_host_password }}
              login_user={{ joomla_db_host_user }}
              password={{ joomla_db_password }}
              priv={{ joomla_db_priv }}
              state=present

- name: Check if Joomla Installation is present
  stat: path={{ server_host_zfs_webroot_dir }}/administrator
  register: joomla_index_file

- name: Download Joomla
  become: false
  local_action: get_url
    url={{ joomla_download_url }}
    dest=./joomla-package.zip
  when: not joomla_index_file.stat.exists

- name: Extract Joomla
  unarchive: copy=yes
             src=./joomla-package.zip
             dest={{ server_host_zfs_webroot_dir }}
             owner=www
             group=www
  when: not joomla_index_file.stat.exists

- name: Update webroot file permissions
  file: path={{ server_host_zfs_webroot_dir }}
        state=directory
        owner=www
        group=www

- name: Delete obsolete files
  file: path={{ item }}
        state=absent
  with_items:
  - '{{ server_host_zfs_webroot_dir }}/robots.txt.dist'
  - '{{ server_host_zfs_webroot_dir }}/web.config.txt'
  - '{{ server_host_zfs_webroot_dir }}/htaccess.txt'

- name: Delete obsolete file (local)
  become: false
  local_action: file
    path=./joomla-package.zip
    state=absent

