---
- name: Install additional packages
  pkgng: name={{ item }}
         state=present
  with_items:
  - py27-MySQLdb

- name: Create Joomla database
  mysql_db: name={{ joomla_db_name }}
            login_host={{ joomla_db_host }}
            login_password={{ joomla_db_host_password }}
            login_user={{ joomla_db_host_user }}
            state=present

- name: Create MariaDB joomla user
  mysql_user: name={{ joomla_db_user }}
              encrypted=no
              host={{ jail_net_ip }}
              login_host={{ joomla_db_host }}
              login_password={{ joomla_db_host_password }}
              login_user={{ joomla_db_host_user }}
              password={{ joomla_db_password }}
              priv={{ joomla_db_priv }}
              state=present

- name: Check if Joomla Installation is present
  stat: path={{ server_webroot_host_zfs_dir }}/administrator
  register: joomla_index_file

- name: Download Joomla
  become: false
  local_action: get_url
    url={{ joomla_download_url }}
    dest=./joomla-package.zip
  when: not joomla_index_file.stat.exists

- name: Extract Joomla
  unarchive:
    copy: 'yes'
    src: './joomla-package.zip'
    dest: '{{ server_webroot_host_zfs_dir }}'
    owner: '{{ sftp_user | default("www") }}'
    group: 'www'
  when: not joomla_index_file.stat.exists

- name: Update webroot file permissions
  file:
    path: '{{ server_webroot_host_zfs_dir }}'
    state: 'directory'
    recurse: 'yes'
    mode: 'u+rw,g-w'
    owner: '{{ sftp_user | default("www") }}'
    group: 'www'

- name: Delete obsolete files
  file: path={{ item }}
        state=absent
  with_items:
  - '{{ server_webroot_host_zfs_dir }}/robots.txt.dist'
  - '{{ server_webroot_host_zfs_dir }}/web.config.txt'
  - '{{ server_webroot_host_zfs_dir }}/htaccess.txt'

- name: Delete obsolete file (local)
  become: false
  local_action: file
    path=./joomla-package.zip
    state=absent

